<a href="https://colab.research.google.com/github/manalrizwan02-cloud/Numpy-/blob/python-library/Numpy_Library_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name:Manal RizwanDewani
Roll.no:879709

Basic Tasks Of Numpy

In [ ]:
# Task 1: Student Marks Analyzer
import numpy as np

Stds_marks = np.array([50,70,80,90,10])
print("Average marks:", np.mean(Stds_marks))
print("Highest marks:",np.max(Stds_marks))
print("Lowest Marks:",np.min(Stds_marks))
print("Total Passed Students :",np.sum(Stds_marks >= 50))
print("Total failed Students:",np.sum(Stds_marks < 50))

Average marks: 60.0
Highest marks: 90
Lowest Marks: 10
Total Passed Students : 4
Total failed Students: 1


In [11]:
#Task 2
import numpy as np

numbers =np.array([10, 20, 30, 40, 50])
print("Total Numbers:",np.sum(numbers))
print("Average Number:",np.mean(numbers))
print("Highest Number:",np.max(numbers))
print("Lowest Number:",np.min(numbers))

Total Numbers: 150
Average Number: 30.0
Highest Number: 50
Lowest Number: 10


In [12]:
#Task 3
import numpy as np

marks=np.array([45, 80, 30, 90, 55, 20])
print(marks[marks>=50])

[80 90 55]


In [13]:
#Task 4
import numpy as np

numbers= np.array([1,2,3,4,5,6])
new_numbers = numbers.reshape(2,3)
print(new_numbers)

[[1 2 3]
 [4 5 6]]


In [14]:
#Task 5
importnumpy as np
marks=np.array([45,50,55,60,66,88,99,62,77,92])

print("Average Marks:",np.mean(marks))
print("Highest Marks:",np.max(marks))
print("Lowest Marks:",np.min(marks))

Average Marks: 69.4
Highest Marks: 99
Lowest Marks: 45


In [16]:
#Task 6
import numpy as np
marks = np.array([35, 67, 89, 45, 90, 22, 70, 58])

passed = marks[marks>=50]
print("Passed Marks:",passed)

fail = marks[marks<50]
print("Fail Marks:",fail)

print("Number of Passed Marks:",len(passed))
print("Number of Fail Marks:",len(fail))

Passed Marks: [67 89 90 70 58]
Fail Marks: [35 45 22]
Number of Passed Marks: 5
Number of Fail Marks: 3


Intermediate Task

In [5]:
#Task 1:Student Performance Analyzer
import numpy as np

marks = np.array([
    [78, 85, 90, 66],
    [55, 72, 68, 80],
    [92, 88, 95, 90],
    [45, 60, 52, 48],
    [70, 75, 65, 82]
])

student_total = np.sum(marks,1)
print("Student Total Marks:", student_total)

student_average = np.mean(marks,1)
print("Students Average Marks:", student_average)

highest_total = np.max(student_total)
print("Student Highest Total Marks:",highest_total)

lowest_total = np.min(student_total)
print("Studnet Lowest Total Marks:",lowest_total)

passed = marks[marks>= 50]
print("Passed Subject Marks:",passed)

fail= marks[marks<50]
print("Fail Subject Marks:",fail)

above_70 = marks[marks>=70]
print("Subject Above 70 Marks:",above_70)

highest_average = np.max(student_average)
print("Highest Average Marks:",highest_average)

sub_average = np.mean(marks,0)
print("Subject Average Marks:",sub_average)

highest_subaverage = np.max(sub_average)
print("Highest Subject Average Marks:",highest_subaverage)

increase_marks = marks +(marks*5/100)
print("After 5% Increased Marks:",increase_marks)

rounded_marks = np.round(increase_marks,2)
print("Round off marks:",rounded_marks)

excellent_marks = marks[marks>=80]
print("Excellent Marks:",excellent_marks)

need_improvement = marks[marks<80]
print("Need Improvement:",need_improvement)

Student Total Marks: [319 275 365 205 292]
Students Average Marks: [79.75 68.75 91.25 51.25 73.  ]
Student Highest Total Marks: 365
Studnet Lowest Total Marks: 205
Passed Subject Marks: [78 85 90 66 55 72 68 80 92 88 95 90 60 52 70 75 65 82]
Fail Subject Marks: [45 48]
Subject Above 70 Marks: [78 85 90 72 80 92 88 95 90 70 75 82]
Highest Average Marks: 91.25
Subject Average Marks: [68.  76.  74.  73.2]
Highest Subject Average Marks: 76.0
After 5% Increased Marks: [[81.9  89.25 94.5  69.3 ]
 [57.75 75.6  71.4  84.  ]
 [96.6  92.4  99.75 94.5 ]
 [47.25 63.   54.6  50.4 ]
 [73.5  78.75 68.25 86.1 ]]
Round off marks: [[81.9  89.25 94.5  69.3 ]
 [57.75 75.6  71.4  84.  ]
 [96.6  92.4  99.75 94.5 ]
 [47.25 63.   54.6  50.4 ]
 [73.5  78.75 68.25 86.1 ]]
Excellent Marks: [85 90 80 92 88 95 90 82]
Need Improvement: [78 66 55 72 68 45 60 52 48 70 75 65]
